sudo: false
language: java
script: mvn verify
jdk:
  - oraclejdk8
after_success:
  - if [ $SONATYPE_USERNAME ]; then
      if [ ! -z "$TRAVIS_TAG" ]; then
        mvn clean deploy --settings .travis/settings.xml;
      fi;
    fi;
