sudo: false
language: java
script: mvn verify
jdk:
  - oraclejdk8
after_success:
  - if [ $SONATYPE_USERNAME ]; then
      echo 'pushing to sonatype with tag $TRAVIS_TAG';
      if [ ! -z "$TRAVIS_TAG" ]; then
        echo 'building';
        mvn clean deploy --settings .travis/settings.xml;
      fi;
    fi;
